name: Run Tests Only

on:
  push:
    branches:
      - main   # รันเมื่อมีการ push ไปที่ branch main
  pull_request:  # หรือเมื่อมีการสร้าง pull request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3   # ดึง source code จาก repository

       - name: Simulate Build
        run: echo "Building project..."

       - name: Simulate Test
        run: echo "Running tests... ✅"

